'use strict';
module.exports = Conversations => {
  const desiredModel = Conversations;
  desiredModel.disableRemoteMethodByName('find', true);
  desiredModel.disableRemoteMethodByName('count', true);
  desiredModel.disableRemoteMethodByName('upsertWithWhere', true);
  desiredModel.disableRemoteMethodByName('replaceOrCreate', true);
  desiredModel.disableRemoteMethodByName('createChangeStream', true);
  desiredModel.disableRemoteMethodByName('patchAttributes', true);
  desiredModel.disableRemoteMethodByName('patchOrCreate', true);
  desiredModel.disableRemoteMethodByName('findOne', true);
  desiredModel.disableRemoteMethodByName('exists', true);
  desiredModel.disableRemoteMethodByName('prototype.patchAttributes', false);
  desiredModel.disableRemoteMethodByName('updateAll', true);
  desiredModel.disableRemoteMethodByName('replaceById', true);
  desiredModel.disableRemoteMethodByName('create', true);
  desiredModel.disableRemoteMethodByName('find', true);
  desiredModel.disableRemoteMethodByName('findById', true);
  desiredModel.disableRemoteMethodByName('deleteById', true);
};
